### ISSUE TITLE
Daccess restriction issue

### ISSUE THREAD

**Issue by realredtext** [system2k/NodeWorldOfText#21]
When a site-denial restriction (daccess;mode=site) is placed on an IP address, the only restriction placed on that IP is the inability to load resources (pages, favicon) from the server, but still allows that IP to connect Websockets to the server, to continue malicious activity when combined with OWOT's client. I will be submitting a PR to this repository soon which will address this issue by checking whether a Websocket's IP address happens to have a site-denial restriction placed upon it, and if so, will send the note to the socket before closing its connection.

**Comment by ntg-lol** [comment]
i never knew about that but cool anyway!
